[package]
name = "nuvolexlauncher"
version = "0.6.5"
description = "Nuvoxel Launcher - Minecraft Launcher"
authors = ["Nuvoxel Launcher"]
edition = "2021"

[lib]
name = "nuvolexlauncher_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-store = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "stream"] }
tokio = { version = "1", features = ["full"] }
sha1_smol = "1"
dirs = "6"
zip = "2"
uuid = { version = "1", features = ["v4"] }
md5 = "0.7"
futures = "0.3"
hex = "0.4"
rfd = "0.15"
base64 = "0.22"
flate2 = "1.0"

