import type { SkinCategory, SkinItem } from "./skins";

const skin = (
  id: string,
  name: string,
  username: string,
  category: SkinCategory,
): SkinItem => ({ id, name, username, category });

export const SKIN_CATALOG_BASE: SkinItem[] = [
  // ── Popular ──
  skin("p01", "Steve", "Steve", "popular"),
  skin("p02", "Alex", "Alex", "popular"),
  skin("p03", "Notch", "Notch", "popular"),
  skin("p04", "Herobrine", "Herobrine", "popular"),
  skin("p05", "Entity 303", "Entity303", "popular"),
  skin("p06", "Null", "Null", "popular"),
  skin("p07", "jeb_", "jeb_", "popular"),
  skin("p08", "Dinnerbone", "Dinnerbone", "popular"),
  skin("p09", "Dream", "Dream", "popular"),
  skin("p10", "Technoblade", "Technoblade", "popular"),
  skin("p11", "Grumm", "Grumm", "popular"),
  skin("p12", "Cyprezz", "Cyprezz", "popular"),
  skin("p13", "LadyAgnes", "LadyAgnes", "popular"),
  skin("p14", "Kingbdogz", "Kingbdogz", "popular"),
  skin("p15", "HelenAngel", "HelenAngel", "popular"),
  skin("p16", "Stampy", "Stampy", "popular"),
  skin("p17", "DanTDM", "DanTDM", "popular"),
  skin("p18", "PopularMMOs", "PopularMMOs", "popular"),
  skin("p19", "ExplodingTNT", "ExplodingTNT", "popular"),
  skin("p20", "Preston", "Preston", "popular"),
  skin("p21", "Unspeakable", "Unspeakable", "popular"),
  skin("p22", "Ssundee", "Ssundee", "popular"),
  skin("p23", "Crainer", "Crainer", "popular"),
  skin("p24", "Grian", "Grian", "popular"),
  skin("p25", "Mumbo", "Mumbo", "popular"),
  skin("p26", "Iskall", "Iskall", "popular"),
  skin("p27", "GoodTimesWithScar", "GoodTimesWithScar", "popular"),
  skin("p28", "Xisuma", "Xisuma", "popular"),
  skin("p29", "AntVenom", "AntVenom", "popular"),
  skin("p30", "SkyDoesMinecraft", "SkyDoesMinecraft", "popular"),
  skin("p31", "JeromeASF", "JeromeASF", "popular"),
  skin("p32", "BajanCanadian", "BajanCanadian", "popular"),
  skin("p33", "Moose", "Moose", "popular"),
  skin("p34", "Jelly", "Jelly", "popular"),
  skin("p35", "Hypnotizd", "Hypnotizd", "popular"),
  skin("p36", "Deadlox", "Deadlox", "popular"),
  skin("p37", "Vikkstar", "Vikkstar", "popular"),
  skin("p38", "Miniminter", "Miniminter", "popular"),
  skin("p39", "Zerkaa", "Zerkaa", "popular"),
  skin("p40", "W2S", "W2S", "popular"),

  // ── Boys / YouTubers ──
  skin("b01", "TommyInnit", "TommyInnit", "boys"),
  skin("b02", "Tubbo", "Tubbo", "boys"),
  skin("b03", "Ranboo", "Ranboo", "boys"),
  skin("b04", "Wilbur Soot", "WilburSoot", "boys"),
  skin("b05", "Philza", "Ph1LzA", "boys"),
  skin("b06", "BadBoyHalo", "BadBoyHalo", "boys"),
  skin("b07", "Skeppy", "Skeppy", "boys"),
  skin("b08", "Sapnap", "Sapnap", "boys"),
  skin("b09", "GeorgeNotFound", "GeorgeNotFound", "boys"),
  skin("b10", "Quackity", "Quackity", "boys"),
  skin("b11", "CaptainSparklez", "CaptainSparklez", "boys"),
  skin("b12", "PewDiePie", "PewDiePie", "boys"),
  skin("b13", "Purpled", "Purpled", "boys"),
  skin("b14", "Illumina", "Illumina", "boys"),
  skin("b15", "Fruitberries", "Fruitberries", "boys"),
  skin("b16", "xNestorio", "xNestorio", "boys"),
  skin("b17", "Fundy", "Fundy", "boys"),
  skin("b18", "Slimecicle", "Slimecicle", "boys"),
  skin("b19", "Technoblade", "Technoblade", "boys"),
  skin("b20", "TapL", "TapL", "boys"),
  skin("b21", "Punz", "Punz", "boys"),
  skin("b22", "Dream", "Dream", "boys"),
  skin("b23", "Antfrost", "Antfrost", "boys"),
  skin("b24", "VelvetIsCake", "VelvetIsCake", "boys"),
  skin("b25", "5up", "5up", "boys"),
  skin("b26", "Hannahxxrose", "Hannahxxrose", "boys"),
  skin("b27", "ItzRealMe", "ItzRealMe", "boys"),
  skin("b28", "Krtzyy", "Krtzyy", "boys"),
  skin("b29", "Eret", "Eret", "boys"),
  skin("b30", "Nihachu", "Nihachu", "boys"),
  skin("b31", "ToxicCoder", "ToxicCoder", "boys"),
  skin("b32", "Wisp", "Wisp", "boys"),
  skin("b33", "Miniminter", "Miniminter", "boys"),
  skin("b34", "KSI", "KSI", "boys"),
  skin("b35", "Beaulo", "Beaulo", "boys"),
  skin("b36", "Shroud", "Shroud", "boys"),
  skin("b37", "Ninja", "Ninja", "boys"),
  skin("b38", "Tfue", "Tfue", "boys"),
  skin("b39", "DrDisrespect", "DrDisrespect", "boys"),
  skin("b40", "xQc", "xQc", "boys"),
  skin("b41", "Ludwig", "Ludwig", "boys"),
  skin("b42", "MoistCr1tikal", "MoistCr1tikal", "boys"),
  skin("b43", "HasanAbi", "HasanAbi", "boys"),
  skin("b44", "Sykkuno", "Sykkuno", "boys"),
  skin("b45", "Corpse", "Corpse", "boys"),
  skin("b46", "Toast", "DisguisedToast", "boys"),
  skin("b47", "Michael", "Michael", "boys"),
  skin("b48", "Gavin", "Gavin", "boys"),
  skin("b49", "Ray", "Ray", "boys"),
  skin("b50", "Jack", "Jack", "boys"),

  // ── Girls ──
  skin("g01", "Aphmau", "Aphmau", "girls"),
  skin("g02", "LDShadowLady", "LDShadowLady", "girls"),
  skin("g03", "StacyPlays", "StacyPlays", "girls"),
  skin("g04", "iHasCupquake", "iHasCupquake", "girls"),
  skin("g05", "ItsFunneh", "ItsFunneh", "girls"),
  skin("g06", "MeganPlays", "MeganPlays", "girls"),
  skin("g07", "Roxycraft", "Roxycraft", "girls"),
  skin("g08", "Omgitsfirefoxx", "Omgitsfirefoxx", "girls"),
  skin("g09", "Shubble", "Shubble", "girls"),
  skin("g10", "StrawberryShortcake", "StrawberryShort", "girls"),
  skin("g11", "Pokimane", "Pokimane", "girls"),
  skin("g12", "Valkyrae", "Valkyrae", "girls"),
  skin("g13", "LilyPichu", "LilyPichu", "girls"),
  skin("g14", "QuarterJade", "QuarterJade", "girls"),
  skin("g15", "Fuslie", "Fuslie", "girls"),
  skin("g16", "Botez", "Botez", "girls"),
  skin("g17", "Amouranth", "Amouranth", "girls"),
  skin("g18", "Nihachu", "Nihachu", "girls"),
  skin("g19", "Hannahxxrose", "Hannahxxrose", "girls"),
  skin("g20", "Tubbo", "Tubbo", "girls"),
  skin("g21", "Emma", "Emma", "girls"),
  skin("g22", "Olivia", "Olivia", "girls"),
  skin("g23", "Sophia", "Sophia", "girls"),
  skin("g24", "Isabella", "Isabella", "girls"),
  skin("g25", "Mia", "Mia", "girls"),
  skin("g26", "Charlotte", "Charlotte", "girls"),
  skin("g27", "Amelia", "Amelia", "girls"),
  skin("g28", "Harper", "Harper", "girls"),
  skin("g29", "Evelyn", "Evelyn", "girls"),
  skin("g30", "Abigail", "Abigail", "girls"),
  skin("g31", "Emily", "Emily", "girls"),
  skin("g32", "Elizabeth", "Elizabeth", "girls"),
  skin("g33", "Sofia", "Sofia", "girls"),
  skin("g34", "Avery", "Avery", "girls"),
  skin("g35", "Ella", "Ella", "girls"),
  skin("g36", "Scarlett", "Scarlett", "girls"),
  skin("g37", "Grace", "Grace", "girls"),
  skin("g38", "Chloe", "Chloe", "girls"),
  skin("g39", "Victoria", "Victoria", "girls"),
  skin("g40", "Riley", "Riley", "girls"),

  // ── Anime ──
  skin("a01", "Naruto", "Naruto", "anime"),
  skin("a02", "Goku", "Goku", "anime"),
  skin("a03", "Sasuke", "Sasuke", "anime"),
  skin("a04", "Luffy", "Luffy", "anime"),
  skin("a05", "Eren", "Eren", "anime"),
  skin("a06", "Levi", "Levi", "anime"),
  skin("a07", "Deku", "Deku", "anime"),
  skin("a08", "Bakugo", "Bakugo", "anime"),
  skin("a09", "Tanjiro", "Tanjiro", "anime"),
  skin("a10", "Nezuko", "Nezuko", "anime"),
  skin("a11", "Gojo", "Gojo", "anime"),
  skin("a12", "Sakura", "Sakura", "anime"),
  skin("a13", "Ichigo", "Ichigo", "anime"),
  skin("a14", "Kirito", "Kirito", "anime"),
  skin("a15", "Asuna", "Asuna", "anime"),
  skin("a16", "Vegeta", "Vegeta", "anime"),
  skin("a17", "Piccolo", "Piccolo", "anime"),
  skin("a18", "Gohan", "Gohan", "anime"),
  skin("a19", "Trunks", "Trunks", "anime"),
  skin("a20", "Broly", "Broly", "anime"),
  skin("a21", "Itachi", "Itachi", "anime"),
  skin("a22", "Kakashi", "Kakashi", "anime"),
  skin("a23", "Minato", "Minato", "anime"),
  skin("a24", "Pain", "Pain", "anime"),
  skin("a25", "Madara", "Madara", "anime"),
  skin("a26", "Zoro", "Zoro", "anime"),
  skin("a27", "Sanji", "Sanji", "anime"),
  skin("a28", "Nami", "Nami", "anime"),
  skin("a29", "Robin", "Robin", "anime"),
  skin("a30", "Ace", "Ace", "anime"),
  skin("a31", "Mikasa", "Mikasa", "anime"),
  skin("a32", "Armin", "Armin", "anime"),
  skin("a33", "Reiner", "Reiner", "anime"),
  skin("a34", "Todoroki", "Todoroki", "anime"),
  skin("a35", "AllMight", "AllMight", "anime"),
  skin("a36", "Denki", "Denki", "anime"),
  skin("a37", "Kirishima", "Kirishima", "anime"),
  skin("a38", "Inosuke", "Inosuke", "anime"),
  skin("a39", "Zenitsu", "Zenitsu", "anime"),
  skin("a40", "Rengoku", "Rengoku", "anime"),
  skin("a41", "Sukuna", "Sukuna", "anime"),
  skin("a42", "Yuji", "Yuji", "anime"),
  skin("a43", "Megumi", "Megumi", "anime"),
  skin("a44", "Nobara", "Nobara", "anime"),
  skin("a45", "Light", "Light", "anime"),
  skin("a46", "L", "L", "anime"),
  skin("a47", "Saitama", "Saitama", "anime"),
  skin("a48", "Genos", "Genos", "anime"),
  skin("a49", "Rem", "Rem", "anime"),
  skin("a50", "Emilia", "Emilia", "anime"),
  skin("a51", "Subaru", "Subaru", "anime"),
  skin("a52", "Kaneki", "Kaneki", "anime"),
  skin("a53", "Touka", "Touka", "anime"),
  skin("a54", "ErenYeager", "ErenYeager", "anime"),
  skin("a55", "Hinata", "Hinata", "anime"),
  skin("a56", "Kageyama", "Kageyama", "anime"),
  skin("a57", "LeviAckerman", "LeviAckerman", "anime"),
  skin("a58", "Miku", "Miku", "anime"),
  skin("a59", "Rin", "Rin", "anime"),
  skin("a60", "Saber", "Saber", "anime"),

  // ── Animals ──
  skin("an01", "Wolf", "Wolf", "animals"),
  skin("an02", "Fox", "Fox", "animals"),
  skin("an03", "Cat", "Cat", "animals"),
  skin("an04", "Panda", "Panda", "animals"),
  skin("an05", "Bear", "Bear", "animals"),
  skin("an06", "Rabbit", "Rabbit", "animals"),
  skin("an07", "Lion", "Lion", "animals"),
  skin("an08", "Penguin", "Penguin", "animals"),
  skin("an09", "Shark", "Shark", "animals"),
  skin("an10", "Eagle", "Eagle", "animals"),
  skin("an11", "Tiger", "Tiger", "animals"),
  skin("an12", "Dragon", "Dragon", "animals"),
  skin("an13", "Dog", "Dog", "animals"),
  skin("an14", "Horse", "Horse", "animals"),
  skin("an15", "Cow", "Cow", "animals"),
  skin("an16", "Pig", "Pig", "animals"),
  skin("an17", "Sheep", "Sheep", "animals"),
  skin("an18", "Chicken", "Chicken", "animals"),
  skin("an19", "Duck", "Duck", "animals"),
  skin("an20", "Owl", "Owl", "animals"),
  skin("an21", "Snake", "Snake", "animals"),
  skin("an22", "Frog", "Frog", "animals"),
  skin("an23", "Monkey", "Monkey", "animals"),
  skin("an24", "Gorilla", "Gorilla", "animals"),
  skin("an24b", "Elephant", "Elephant", "animals"),
  skin("an25", "Giraffe", "Giraffe", "animals"),
  skin("an26", "Zebra", "Zebra", "animals"),
  skin("an27", "Crocodile", "Crocodile", "animals"),
  skin("an28", "Dolphin", "Dolphin", "animals"),
  skin("an29", "Whale", "Whale", "animals"),
  skin("an30", "Bat", "Bat", "animals"),

  // ── Fashion ──
  skin("f01", "Fashionista", "Fashionista", "fashion"),
  skin("f02", "Street Style", "StreetStyle", "fashion"),
  skin("f03", "Cyber Punk", "CyberPunk", "fashion"),
  skin("f04", "Neon Glow", "NeonGlow", "fashion"),
  skin("f05", "Royal Knight", "RoyalKnight", "fashion"),
  skin("f06", "Dark Mage", "DarkMage", "fashion"),
  skin("f07", "Snow Queen", "SnowQueen", "fashion"),
  skin("f08", "Summer Vibes", "SummerVibes", "fashion"),
  skin("f09", "Hoodie Boy", "HoodieBoy", "fashion"),
  skin("f10", "Hoodie Girl", "HoodieGirl", "fashion"),
  skin("f11", "Business Suit", "BusinessSuit", "fashion"),
  skin("f12", "Casual Cool", "CasualCool", "fashion"),
  skin("f13", "Pastel Dream", "PastelDream", "fashion"),
  skin("f14", "Gothic", "Gothic", "fashion"),
  skin("f15", "Steampunk", "Steampunk", "fashion"),
  skin("f16", "Astronaut", "Astronaut", "fashion"),
  skin("f17", "Pilot", "Pilot", "fashion"),
  skin("f18", "Doctor", "Doctor", "fashion"),
  skin("f19", "Chef", "Chef", "fashion"),
  skin("f20", "Police", "Police", "fashion"),
  skin("f21", "Firefighter", "Firefighter", "fashion"),
  skin("f22", "Ninja Fashion", "NinjaFashion", "fashion"),
  skin("f23", "Samurai", "Samurai", "fashion"),
  skin("f24", "Viking", "Viking", "fashion"),
  skin("f25", "Pirate", "Pirate", "fashion"),
  skin("f26", "Cowboy", "Cowboy", "fashion"),
  skin("f27", "Surfer", "Surfer", "fashion"),
  skin("f28", "Skater", "Skater", "fashion"),
  skin("f29", "DJ", "DJ", "fashion"),
  skin("f30", "Rockstar", "Rockstar", "fashion"),

  // ── Games ──
  skin("gm01", "Mario", "Mario", "games"),
  skin("gm02", "Luigi", "Luigi", "games"),
  skin("gm03", "Sonic", "Sonic", "games"),
  skin("gm04", "Link", "Link", "games"),
  skin("gm05", "Zelda", "Zelda", "games"),
  skin("gm06", "Kirby", "Kirby", "games"),
  skin("gm07", "Pikachu", "Pikachu", "games"),
  skin("gm08", "Ash", "Ash", "games"),
  skin("gm09", "Charizard", "Charizard", "games"),
  skin("gm10", "Master Chief", "MasterChief", "games"),
  skin("gm11", "Steve MC", "Steve", "games"),
  skin("gm12", "Alex MC", "Alex", "games"),
  skin("gm13", "Creeper", "Creeper", "games"),
  skin("gm14", "Enderman", "Enderman", "games"),
  skin("gm15", "Skeleton", "Skeleton", "games"),
  skin("gm16", "Zombie", "Zombie", "games"),
  skin("gm17", "Wither", "Wither", "games"),
  skin("gm18", "Herobrine", "Herobrine", "games"),
  skin("gm19", "Roblox", "Roblox", "games"),
  skin("gm20", "Fortnite", "Fortnite", "games"),
  skin("gm21", "Among Us", "AmongUs", "games"),
  skin("gm22", "Geralt", "Geralt", "games"),
  skin("gm23", "Kratos", "Kratos", "games"),
  skin("gm24", "Lara Croft", "LaraCroft", "games"),
  skin("gm25", "Steve Fortnite", "SteveFortnite", "games"),
  skin("gm26", "Tracer", "Tracer", "games"),
  skin("gm27", "Genji", "Genji", "games"),
  skin("gm28", "Jinx", "Jinx", "games"),
  skin("gm29", "Yasuo", "Yasuo", "games"),
  skin("gm30", "Steve Halo", "SteveHalo", "games"),
  skin("gm31", "Pacman", "Pacman", "games"),
  skin("gm32", "Tetris", "Tetris", "games"),
  skin("gm33", "Portal", "Portal", "games"),
  skin("gm34", "GLaDOS", "GLaDOS", "games"),
  skin("gm35", "Steve Terraria", "SteveTerraria", "games"),

  // ── Movies / TV ──
  skin("mv01", "Batman", "Batman", "movies"),
  skin("mv02", "Superman", "Superman", "movies"),
  skin("mv03", "Spider-Man", "SpiderMan", "movies"),
  skin("mv04", "Iron Man", "IronMan", "movies"),
  skin("mv05", "Captain America", "CaptainAmerica", "movies"),
  skin("mv06", "Thor", "Thor", "movies"),
  skin("mv07", "Hulk", "Hulk", "movies"),
  skin("mv08", "Deadpool", "Deadpool", "movies"),
  skin("mv09", "Wolverine", "Wolverine", "movies"),
  skin("mv10", "Flash", "Flash", "movies"),
  skin("mv11", "Wonder Woman", "WonderWoman", "movies"),
  skin("mv12", "Joker", "Joker", "movies"),
  skin("mv13", "Harley Quinn", "HarleyQuinn", "movies"),
  skin("mv14", "Darth Vader", "DarthVader", "movies"),
  skin("mv15", "Luke Skywalker", "LukeSkywalker", "movies"),
  skin("mv16", "Yoda", "Yoda", "movies"),
  skin("mv17", "Harry Potter", "HarryPotter", "movies"),
  skin("mv18", "Hermione", "Hermione", "movies"),
  skin("mv19", "Dumbledore", "Dumbledore", "movies"),
  skin("mv20", "Voldemort", "Voldemort", "movies"),
  skin("mv21", "Frodo", "Frodo", "movies"),
  skin("mv22", "Gandalf", "Gandalf", "movies"),
  skin("mv23", "Legolas", "Legolas", "movies"),
  skin("mv24", "Aragorn", "Aragorn", "movies"),
  skin("mv25", "Gollum", "Gollum", "movies"),
  skin("mv26", "Shrek", "Shrek", "movies"),
  skin("mv27", "Donkey", "Donkey", "movies"),
  skin("mv28", "Minions", "Minions", "movies"),
  skin("mv29", "Grinch", "Grinch", "movies"),
  skin("mv30", "Jack Sparrow", "JackSparrow", "movies"),

  // ── PVP / Competitive ──
  skin("pv01", "PvP King", "PvPKing", "pvp"),
  skin("pv02", "Combo Master", "ComboMaster", "pvp"),
  skin("pv03", "Crit God", "CritGod", "pvp"),
  skin("pv04", "Block Hit", "BlockHit", "pvp"),
  skin("pv05", "W Tap", "WTap", "pvp"),
  skin("pv06", "Strafe", "Strafe", "pvp"),
  skin("pv07", "Rod God", "RodGod", "pvp"),
  skin("pv08", "Bow God", "BowGod", "pvp"),
  skin("pv09", "Pot God", "PotGod", "pvp"),
  skin("pv10", "Sword PvP", "SwordPvP", "pvp"),
  skin("pv11", "Axe PvP", "AxePvP", "pvp"),
  skin("pv12", "UHC King", "UHCKing", "pvp"),
  skin("pv13", "Bedwars Pro", "BedwarsPro", "pvp"),
  skin("pv14", "Skywars Pro", "SkywarsPro", "pvp"),
  skin("pv15", "Duels Master", "DuelsMaster", "pvp"),
  skin("pv16", "Hypixel", "Hypixel", "pvp"),
  skin("pv17", "Mineplex", "Mineplex", "pvp"),
  skin("pv18", "Cubecraft", "Cubecraft", "pvp"),
  skin("pv19", "Hive", "Hive", "pvp"),
  skin("pv20", "Badlion", "Badlion", "pvp"),
  skin("pv21", "Lunar Client", "LunarClient", "pvp"),
  skin("pv22", "Feather Client", "FeatherClient", "pvp"),
  skin("pv23", "Labymod", "Labymod", "pvp"),
  skin("pv24", "PvP Legend", "PvPLegend", "pvp"),
  skin("pv25", "Ranked #1", "Ranked1", "pvp"),

  // ── Medieval / Fantasy ──
  skin("md01", "Knight", "Knight", "medieval"),
  skin("md02", "Paladin", "Paladin", "medieval"),
  skin("md03", "Archer", "Archer", "medieval"),
  skin("md04", "Wizard", "Wizard", "medieval"),
  skin("md05", "Warlock", "Warlock", "medieval"),
  skin("md06", "Cleric", "Cleric", "medieval"),
  skin("md07", "Barbarian", "Barbarian", "medieval"),
  skin("md08", "Rogue", "Rogue", "medieval"),
  skin("md09", "Assassin", "Assassin", "medieval"),
  skin("md10", "King", "King", "medieval"),
  skin("md11", "Queen", "Queen", "medieval"),
  skin("md12", "Prince", "Prince", "medieval"),
  skin("md13", "Princess", "Princess", "medieval"),
  skin("md14", "Dragon Slayer", "DragonSlayer", "medieval"),
  skin("md15", "Elf", "Elf", "medieval"),
  skin("md16", "Dwarf", "Dwarf", "medieval"),
  skin("md17", "Orc", "Orc", "medieval"),
  skin("md18", "Goblin", "Goblin", "medieval"),
  skin("md19", "Troll", "Troll", "medieval"),
  skin("md20", "Phoenix", "Phoenix", "medieval"),
  skin("md21", "Griffin", "Griffin", "medieval"),
  skin("md22", "Unicorn", "Unicorn", "medieval"),
  skin("md23", "Fairy", "Fairy", "medieval"),
  skin("md24", "Demon", "Demon", "medieval"),
  skin("md25", "Angel", "Angel", "medieval"),

  // ── Horror / Creepy ──
  skin("hr01", "Slenderman", "Slenderman", "horror"),
  skin("hr02", "Jeff", "Jeff", "horror"),
  skin("hr03", "Smile Dog", "SmileDog", "horror"),
  skin("hr04", "Creepypasta", "Creepypasta", "horror"),
  skin("hr05", "Ghost", "Ghost", "horror"),
  skin("hr06", "Zombie Horror", "ZombieHorror", "horror"),
  skin("hr07", "Skeleton King", "SkeletonKing", "horror"),
  skin("hr08", "Vampire", "Vampire", "horror"),
  skin("hr09", "Werewolf", "Werewolf", "horror"),
  skin("hr10", "Witch", "Witch", "horror"),
  skin("hr11", "Clown", "Clown", "horror"),
  skin("hr12", "Pennywise", "Pennywise", "horror"),
  skin("hr13", "Freddy", "Freddy", "horror"),
  skin("hr14", "Jason", "Jason", "horror"),
  skin("hr15", "Michael Myers", "MichaelMyers", "horror"),
  skin("hr16", "Scream", "Scream", "horror"),
  skin("hr17", "Annabelle", "Annabelle", "horror"),
  skin("hr18", "Chucky", "Chucky", "horror"),
  skin("hr19", "Entity", "Entity", "horror"),
  skin("hr20", "Null Horror", "NullHorror", "horror"),

  // ── Superheroes ──
  skin("sh01", "Batman", "Batman", "superheroes"),
  skin("sh02", "Superman", "Superman", "superheroes"),
  skin("sh03", "Spider-Man", "SpiderMan", "superheroes"),
  skin("sh04", "Iron Man", "IronMan", "superheroes"),
  skin("sh05", "Captain America", "CaptainAmerica", "superheroes"),
  skin("sh06", "Thor", "Thor", "superheroes"),
  skin("sh07", "Hulk", "Hulk", "superheroes"),
  skin("sh08", "Black Widow", "BlackWidow", "superheroes"),
  skin("sh09", "Hawkeye", "Hawkeye", "superheroes"),
  skin("sh10", "Ant-Man", "AntMan", "superheroes"),
  skin("sh11", "Wasp", "Wasp", "superheroes"),
  skin("sh12", "Doctor Strange", "DoctorStrange", "superheroes"),
  skin("sh13", "Black Panther", "BlackPanther", "superheroes"),
  skin("sh14", "Captain Marvel", "CaptainMarvel", "superheroes"),
  skin("sh15", "Scarlet Witch", "ScarletWitch", "superheroes"),
  skin("sh16", "Vision", "Vision", "superheroes"),
  skin("sh17", "Loki", "Loki", "superheroes"),
  skin("sh18", "Thanos", "Thanos", "superheroes"),
  skin("sh19", "Deadpool", "Deadpool", "superheroes"),
  skin("sh20", "Wolverine", "Wolverine", "superheroes"),
  skin("sh21", "Flash", "Flash", "superheroes"),
  skin("sh22", "Aquaman", "Aquaman", "superheroes"),
  skin("sh23", "Green Lantern", "GreenLantern", "superheroes"),
  skin("sh24", "Wonder Woman", "WonderWoman", "superheroes"),
  skin("sh25", "Robin", "Robin", "superheroes"),

  // ── Memes / Fun ──
  skin("mm01", "Doge", "Doge", "memes"),
  skin("mm02", "Pepe", "Pepe", "memes"),
  skin("mm03", "Shrek", "Shrek", "memes"),
  skin("mm04", "Rick Roll", "RickRoll", "memes"),
  skin("mm05", "Nyan Cat", "NyanCat", "memes"),
  skin("mm06", "Trollface", "Trollface", "memes"),
  skin("mm07", "Among Us Meme", "AmongUsMeme", "memes"),
  skin("mm08", "Sus", "Sus", "memes"),
  skin("mm09", "Amogus", "Amogus", "memes"),
  skin("mm10", "Skibidi", "Skibidi", "memes"),
  skin("mm11", "Sigma", "Sigma", "memes"),
  skin("mm12", "Gigachad", "Gigachad", "memes"),
  skin("mm13", "Wojak", "Wojak", "memes"),
  skin("mm14", "Chad", "Chad", "memes"),
  skin("mm15", "Karen", "Karen", "memes"),
  skin("mm16", "Boomer", "Boomer", "memes"),
  skin("mm17", "Zoomer", "Zoomer", "memes"),
  skin("mm18", "Noob", "Noob", "memes"),
  skin("mm19", "Pro", "Pro", "memes"),
  skin("mm20", "Hacker", "Hacker", "memes"),
  skin("mm21", "Bot", "Bot", "memes"),
  skin("mm22", "AFK", "AFK", "memes"),
  skin("mm23", "Lag", "Lag", "memes"),
  skin("mm24", "404", "404", "memes"),
  skin("mm25", "Steve Meme", "SteveMeme", "memes"),

  // ── Extra popular / streamers ──
  skin("x01", "Karl", "Karl", "popular"),
  skin("x02", "Quackity", "Quackity", "popular"),
  skin("x03", "Foolish", "Foolish", "popular"),
  skin("x04", "Slimecicle", "Slimecicle", "popular"),
  skin("x05", "Connor", "Connor", "popular"),
  skin("x06", "Joey", "Joey", "popular"),
  skin("x07", "Scar", "Scar", "popular"),
  skin("x08", "GeminiTay", "GeminiTay", "popular"),
  skin("x09", "ImpulseSV", "ImpulseSV", "popular"),
  skin("x10", "TangoTek", "TangoTek", "popular"),
  skin("x11", "Cubfan135", "Cubfan135", "popular"),
  skin("x12", "FalseSymmetry", "FalseSymmetry", "popular"),
  skin("x13", "Stressmonster101", "Stressmonster101", "popular"),
  skin("x14", "Zedaph", "Zedaph", "popular"),
  skin("x15", "Rendog", "Rendog", "popular"),
  skin("x16", "Docm77", "Docm77", "popular"),
  skin("x17", "XBCrafted", "XBCrafted", "popular"),
  skin("x18", "Etho", "Etho", "popular"),
  skin("x19", "VintageBeef", "VintageBeef", "popular"),
  skin("x20", "PauseUnpause", "PauseUnpause", "popular"),

  // ── More anime ──
  skin("xa01", "Vegeta Blue", "VegetaBlue", "anime"),
  skin("xa02", "Frieza", "Frieza", "anime"),
  skin("xa03", "Cell", "Cell", "anime"),
  skin("xa04", "Beerus", "Beerus", "anime"),
  skin("xa05", "Whis", "Whis", "anime"),
  skin("xa06", "Jiren", "Jiren", "anime"),
  skin("xa07", "Kakashi Hatake", "KakashiHatake", "anime"),
  skin("xa08", "Obito", "Obito", "anime"),
  skin("xa09", "Gaara", "Gaara", "anime"),
  skin("xa10", "Rock Lee", "RockLee", "anime"),
  skin("xa11", "Shikamaru", "Shikamaru", "anime"),
  skin("xa12", "Tsunade", "Tsunade", "anime"),
  skin("xa13", "Jiraiya", "Jiraiya", "anime"),
  skin("xa14", "Sanemi", "Sanemi", "anime"),
  skin("xa15", "Shinobu", "Shinobu", "anime"),
  skin("xa16", "Mitsuri", "Mitsuri", "anime"),
  skin("xa17", "Tengen", "Tengen", "anime"),
  skin("xa18", "Muichiro", "Muichiro", "anime"),
  skin("xa19", "Giyu", "Giyu", "anime"),
  skin("xa20", "Kanao", "Kanao", "anime"),

  // ── More games ──
  skin("xg01", "Steve Smash", "SteveSmash", "games"),
  skin("xg02", "Isabelle", "Isabelle", "games"),
  skin("xg03", "Steve SSB", "SteveSSB", "games"),
  skin("xg04", "Sans", "Sans", "games"),
  skin("xg05", "Papyrus", "Papyrus", "games"),
  skin("xg06", "Frisk", "Frisk", "games"),
  skin("xg07", "Chara", "Chara", "games"),
  skin("xg08", "Steve Hollow", "SteveHollow", "games"),
  skin("xg09", "Steve Elden", "SteveElden", "games"),
  skin("xg10", "Steve GTA", "SteveGTA", "games"),
  skin("xg11", "Steve CS", "SteveCS", "games"),
  skin("xg12", "Steve Valorant", "SteveValorant", "games"),
  skin("xg13", "Steve Apex", "SteveApex", "games"),
  skin("xg14", "Steve LoL", "SteveLoL", "games"),
  skin("xg15", "Steve Dota", "SteveDota", "games"),

  // ── More medieval ──
  skin("xm01", "Blacksmith", "Blacksmith", "medieval"),
  skin("xm02", "Merchant", "Merchant", "medieval"),
  skin("xm03", "Farmer", "Farmer", "medieval"),
  skin("xm04", "Guard", "Guard", "medieval"),
  skin("xm05", "Captain", "Captain", "medieval"),
  skin("xm06", "General", "General", "medieval"),
  skin("xm07", "Emperor", "Emperor", "medieval"),
  skin("xm08", "Empress", "Empress", "medieval"),
  skin("xm09", "Monk", "Monk", "medieval"),
  skin("xm10", "Nun", "Nun", "medieval"),
  skin("xm11", "Bard", "Bard", "medieval"),
  skin("xm12", "Druid", "Druid", "medieval"),
  skin("xm13", "Necromancer", "Necromancer", "medieval"),
  skin("xm14", "Summoner", "Summoner", "medieval"),
  skin("xm15", "Alchemist", "Alchemist", "medieval"),
];
